version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: vrm_postgres
    environment:
      POSTGRES_DB: vrm_db
      POSTGRES_USER: vrm_user
      POSTGRES_PASSWORD: vrm_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vrm_redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: vrm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vrm.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
